apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker

spec:
  replicas: 1

  selector:
    matchLabels:
      app: worker

  template:
    metadata:
      labels:
        app: worker

    spec:
      containers:
        - name: worker
          image: ghcr.io/iboqvist/dd2482-keda-app:latest
          imagePullPolicy: Always

          env:
            - name: RABBITMQ_HOST
              value: rabbitmq

            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: username

            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: password

            - name: QUEUE_NAME
              value: task_queue

            - name: PROCESSING_TIME
              value: "1"

          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"

            limits:
              cpu: "500m"
              memory: "128Mi"